### ISSUE TITLE
CPU Share grouping by logical or physical hostname

### ISSUE THREAD

**Issue by feature76** [ITGAIN/s4dbs_custom_boards#14]
Hi!
We are using for hadr many virtual ip-Adresses on one physical host and would like to use this new System Resourxce CPU Share dashboard for monitoring cpu-usage on one dashboard.
Physical hostname is already collected, but does not show all virtual ips on that host.
It would be great if we could switch between logical and physical hostname for grouping in that dashboard.

Thanky you!
Kind regards,
Ronny Schneider

**Comment by maggusf** [comment]
integrated a few moments ago
